### ISSUE TITLE
OutOfMemoryError on Stetho on accesing Heavy Post Data

### ISSUE THREAD

**Issue by mwshubham** [mwshubham/WordpressApp#7]
`  java.lang.OutOfMemoryError: Failed to allocate a 41560 byte allocation with 23736 free bytes and 23KB until OOM, max allowed footprint 16777216, growth limit 16777216
                                                            at android.database.CursorWindow.nativeGetString(Native Method)
                                                            at android.database.CursorWindow.getString(CursorWindow.java:438)
                                                            at android.database.AbstractWindowedCursor.getString(AbstractWindowedCursor.java:51)
                                                            at com.facebook.stetho.inspector.protocol.module.Database.flattenRows(Database.java:209)
                                                            at com.facebook.stetho.inspector.protocol.module.Database.access$200(Database.java:45)
                                                            at com.facebook.stetho.inspector.protocol.module.Database$1.handleSelect(Database.java:147)
                                                            at com.facebook.stetho.inspector.protocol.module.Database$1.handleSelect(Database.java:132)
                                                            at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.executeSelect(SqliteDatabaseDriver.java:212)
                                                            at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.executeSQL(SqliteDatabaseDriver.java:172)
                                                            at com.facebook.stetho.inspector.database.SqliteDatabaseDriver.executeSQL(SqliteDatabaseDriver.java:34)
                                                            at com.facebook.stetho.inspector.protocol.module.Database.executeSQL(Database.java:129)
                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                            at com.facebook.stetho.inspector.MethodDispatcher$MethodDispatchHelper.invoke(MethodDispatcher.java:96)
                                                            at com.facebook.stetho.inspector.MethodDispatcher.dispatch(MethodDispatcher.java:67)
                                                            at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteRequest(ChromeDevtoolsServer.java:129)
                                                            at com.facebook.stetho.inspector.ChromeDevtoolsServer.handleRemoteMessage(ChromeDevtoolsServer.java:111)
                                                            at com.facebook.stetho.inspector.ChromeDevtoolsServer.onMessage(ChromeDevtoolsServer.java:87)
                                                            at com.facebook.stetho.websocket.WebSocketSession$1.handleTextFrame(WebSocketSession.java:176)
                                                            at com.facebook.stetho.websocket.WebSocketSession$1.onCompleteFrame(WebSocketSession.java:136)
                                                            at com.facebook.stetho.websocket.ReadHandler.readLoop(ReadHandler.java:44)
                                                            at com.facebook.stetho.websocket.WebSocketSession.handle(WebSocketSession.java:45)
                                                            at com.facebook.stetho.websocket.WebSocketHandler.doUpgrade(WebSocketHandler.java:117)
                                                            at com.facebook.stetho.websocket.WebSocketHandler.handleRequest(WebSocketHandler.java:83)
                                                            at com.facebook.stetho.server.http.LightHttpServer.dispatchToHandler(LightHttpServer.java:84)
                                                            at com.facebook.stetho.server.http.LightHttpServer.serve(LightHttpServer.java:61)
                                                            at com.facebook.stetho.inspector.DevtoolsSocketHandler.onAccepted(DevtoolsSocketHandler.java:52)
                                                            at com.facebook.stetho.server.ProtocolDetectingSocketHandler.onSecured(ProtocolDetectingSocketHandler.java:63)
                                                            at com.facebook.stetho.server.SecureSocketHandler.onAccepted(SecureSocketHandler.java:33)
                                                            at com.facebook.stetho.server.LazySocketHandler.onAccepted(LazySocketHandler.java:36)
                                                            at com.facebook.stetho.server.LocalSocketServer$WorkerThread.run(LocalSocketServer.java:167)`

**Comment by bacarybruno** [comment]
Hi, did you find a solution?
